### PR TITLE
More complete html elements

### LINKED ISSUE #2: Deprecated elements & attributes
It would be a nice addition to distinguish deprecated elements & deprecated attributes. If you're okay I can try to update your script to include that.

### PR DESCRIPTION
**Pull request by artyuum**
Closes #2

As a bonus, it also handles experimental elements & attributes.

PS: I'm not a Python dev. some parts could probably be optimized. Feel free to make suggestions.

### CODE REVIEW

**Comment by artyuum** [comment]
@jozo I still need to add the global attributes then I'll be done. But you can still let me know what you think.

**Comment by artyuum** [comment]
The script could also scrap the "non standard" indicator for the attributes. (e.g. [anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/anchor))

I'm not sure what's the difference between "non standard" and "experimental" but it's an additional information from the mdn website that we can add to the JSON output.

What do you think? Should I implement that in this PR or in a separate one?

**Comment by artyuum** [comment]
Sorry for the messy work. I found some elements where the scraping didn't work. It's fixed now.

**Comment by jozo** [comment]
Sorry for the late response. It looks good, thank you @artyuum :+1:

**Pull request merged**
